docs_dir: docs/book
site_dir: docs/html
nav:
    - { Home: index.md }
    - { Introduction: intro.md }
site_name: laminas-mvc-middleware
site_description: 'Dispatch middleware pipelines in place of controllers in laminas-mvc.'
repo_url: 'https://github.com/laminas/laminas-mvc-middleware'
extra:
    project: Components
    project_url: 'https://docs.laminas.dev'
